version: "3"
services:
  lab:
    env_file: .env
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    hostname: localhost
    working_dir: ${WORK_DIR}
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:${WORK_DIR}
    entrypoint:
      - scripts/run.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
