services:
  test-custom-base:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: custom-base
    volumes:
      - ./check_cuda.sh:/check_cuda.sh
    command: sh check_cuda.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
