services:
  test-devel:
    image: nvidia/cuda:11.8.0-devel-ubuntu20.04
    volumes:
      - ./check_cuda.sh:/check_cuda.sh
    command: sh check_cuda.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
