version: "3"
services:
  lab:
    env_file: .env
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    hostname: localhost
    working_dir: ${WORK_DIR}
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:${WORK_DIR}:cached
    entrypoint:
      - scripts/run.sh
